services:
  qlines_app_service:
    build:
      context: ./
      dockerfile: Dockerfile
    image: qlines_app_image
    container_name: qlines_app_container
    privileged: true
    restart: unless-stopped
    ports:
    #  - "7000-7100:7000-7100" # for mqtt and dbs
    #  - "5000:5000"  # gunicorn
      - "127.0.0.1:8000:8000"
      - "127.0.0.1:8001:8001"
      - "0.0.0.0:80:80"
     
    volumes:
      - ./:/opt/qlines_app/


  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
      ME_CONFIG_BASICAUTH: false

networks:
  qlines_net:
    name: custom_qlines_network
