version: '1'
services:
  qlines_app_service:
    build:
      context: ./
      dockerfile: Dockerfile
    image: qlines_app_image
    container_name: qlines_app_container
    restart: unless-stopped
    ports:
    #  - "80:80" # http
    #  - "443:443" # https
    #  - "7000-7100:7000-7100" # for mqtt and dbs
      - "5000:5000"  # gunicorn
      - "127.0.0.1:8000:8000"
      - "127.0.0.1:8001:8001"
     
    volumes:
      - ./:/opt/qlines_app/
    networks:
      - "qlines_net"

networks:
  qlines_net:
    name: custom_qlines_network
