version: '3'

services:
  qlines_app_service:
    build: 
      context: ./
      dockerfile: Dockerfile      
    container_name: qlines_container
    restart: unless-stopped
    ports:
      #- "80:80" # http
      #- "443:443" # https
      - "7000-7100:7000-7100" # for mqtt and dbs
      - "5000:5000"  # gunicorn
    volumes:
      - ./:/opt/qlines_app/
    #networks:
    # - "qlines_net"

# networks:
#   qlines_net:
#     driver: bridge
networks: 
  default: 
    external: 
      name: qlines