
def sample_insta_data_maker():

    image_list = ['https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRgfO1Mq0Kcpp5TjqGOja-AnEFkpFLAav4R0g&usqp=CAU',
                  'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRBwgu1A5zgPSvfE83nurkuzNEoXs9DMNr8Ww&usqp=CAU',
                  'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQGqeiMvcMA8ATx6McIgv0QgGq9njL6_9Q9Ww&usqp=CAU',
                  ]

    data = [
        {'name': 'testname1', 'id': 'testid1', 'avglikesppost': 14, 'postspw': 12,
         'followers': '42345', 'following': 112, 'img': image_list[0]},
        {'name': 'testname2', 'id': 'testid2', 'avglikesppost': 29, 'postspw': 32,
         'followers': '86', 'following': 242,        'img': image_list[1]},
        {'name': 'testname1', 'id': 'testid1', 'avglikesppost': 32, 'postspw': 12,
         'followers': '42345', 'following': 112, 'img': image_list[0]},
        {'name': 'testname2', 'id': 'testid2', 'avglikesppost': 43, 'postspw': 32,
         'followers': '86', 'following': 242,        'img': image_list[1]},
        {'name': 'testname1', 'id': 'testid1', 'avglikesppost': 55, 'postspw': 12,
         'followers': '42345', 'following': 112, 'img': image_list[0]},
        {'name': 'testname2', 'id': 'testid2', 'avglikesppost': 67, 'postspw': 32,
         'followers': '86', 'following': 242,        'img': image_list[1]},
        {'name': 'testname1', 'id': 'testid1', 'avglikesppost': 32, 'postspw': 12,
         'followers': '42345', 'following': 112, 'img': image_list[0]},
        {'name': 'testname2', 'id': 'testid2', 'avglikesppost': 43, 'postspw': 32,
         'followers': '86', 'following': 242,        'img': image_list[1]},
        {'name': 'testname1', 'id': 'testid1', 'avglikesppost': 55, 'postspw': 12,
         'followers': '42345', 'following': 112, 'img': image_list[0]},
        {'name': 'testname2', 'id': 'testid2', 'avglikesppost': 67, 'postspw': 32,
         'followers': '86', 'following': 242,        'img': image_list[1]},
        {'name': 'testname3', 'id': 'testid3', 'avglikesppost': 79, 'postspw': 5,
         'followers': '1593476', 'following': 193,   'img': image_list[2]},
        {'name': 'testname2', 'id': 'testid2', 'avglikesppost': 43, 'postspw': 32,
         'followers': '86', 'following': 242,        'img': image_list[1]},
        {'name': 'testname1', 'id': 'testid1', 'avglikesppost': 55, 'postspw': 12,
         'followers': '42345', 'following': 112, 'img': image_list[0]},
        {'name': 'testname2', 'id': 'testid2', 'avglikesppost': 67, 'postspw': 32,
         'followers': '86', 'following': 242,        'img': image_list[1]},
        {'name': 'testname3', 'id': 'testid3', 'avglikesppost': 79, 'postspw': 5,
         'followers': '1593476', 'following': 193,   'img': image_list[2]},
        {'name': 'testname1', 'id': 'testid1', 'avglikesppost': 32, 'postspw': 12,
         'followers': '42345', 'following': 112, 'img': image_list[0]},
        {'name': 'testname2', 'id': 'testid2', 'avglikesppost': 43, 'postspw': 32,
         'followers': '86', 'following': 242,        'img': image_list[1]},
        {'name': 'testname1', 'id': 'testid1', 'avglikesppost': 55, 'postspw': 12,
         'followers': '42345', 'following': 112, 'img': image_list[0]},
        {'name': 'testname2', 'id': 'testid2', 'avglikesppost': 67, 'postspw': 32,
         'followers': '86', 'following': 242,        'img': image_list[1]},
        {'name': 'testname3', 'id': 'testid3', 'avglikesppost': 79, 'postspw': 5,
         'followers': '1593476', 'following': 193,   'img': image_list[2]},
        {'name': 'testname1', 'id': 'testid1', 'avglikesppost': 55, 'postspw': 12,
         'followers': '42345', 'following': 112, 'img': image_list[0]},
        {'name': 'testname2', 'id': 'testid2', 'avglikesppost': 67, 'postspw': 32,
         'followers': '86', 'following': 242,        'img': image_list[1]},
        {'name': 'testname1', 'id': 'testid1', 'avglikesppost': 32, 'postspw': 12,
         'followers': '42345', 'following': 112, 'img': image_list[0]},
        {'name': 'testname2', 'id': 'testid2', 'avglikesppost': 43, 'postspw': 32,
         'followers': '86', 'following': 242,        'img': image_list[1]},
        {'name': 'testname1', 'id': 'testid1', 'avglikesppost': 55, 'postspw': 12,
         'followers': '42345', 'following': 112, 'img': image_list[0]},
        {'name': 'testname2', 'id': 'testid2', 'avglikesppost': 67, 'postspw': 32,
         'followers': '86', 'following': 242,        'img': image_list[1]},
        {'name': 'testname3', 'id': 'testid3', 'avglikesppost': 79, 'postspw': 5,
         'followers': '1593476', 'following': 193,   'img': image_list[2]},
        {'name': 'testname2', 'id': 'testid2', 'avglikesppost': 43, 'postspw': 32,
         'followers': '86', 'following': 242,        'img': image_list[1]},
        {'name': 'testname1', 'id': 'testid1', 'avglikesppost': 55, 'postspw': 12,
         'followers': '42345', 'following': 112, 'img': image_list[0]},
        {'name': 'testname2', 'id': 'testid2', 'avglikesppost': 67, 'postspw': 32,
         'followers': '86', 'following': 242,        'img': image_list[1]},
        {'name': 'testname3', 'id': 'testid3', 'avglikesppost': 79, 'postspw': 5,
         'followers': '1593476', 'following': 193,   'img': image_list[2]},
        {'name': 'testname1', 'id': 'testid1', 'avglikesppost': 32, 'postspw': 12,
         'followers': '42345', 'following': 112, 'img': image_list[0]},
        {'name': 'testname2', 'id': 'testid2', 'avglikesppost': 43, 'postspw': 32,
         'followers': '86', 'following': 242,        'img': image_list[1]},
        {'name': 'testname1', 'id': 'testid1', 'avglikesppost': 55, 'postspw': 12,
         'followers': '42345', 'following': 112, 'img': image_list[0]},
        {'name': 'testname2', 'id': 'testid2', 'avglikesppost': 67, 'postspw': 32,
         'followers': '86', 'following': 242,        'img': image_list[1]},
        {'name': 'testname3', 'id': 'testid3', 'avglikesppost': 79, 'postspw': 5,
         'followers': '1593476', 'following': 193,   'img': image_list[2]},
        {'name': 'testname1', 'id': 'testid1', 'avglikesppost': 55, 'postspw': 12,
         'followers': '42345', 'following': 112, 'img': image_list[0]},
        {'name': 'testname2', 'id': 'testid2', 'avglikesppost': 67, 'postspw': 32,
         'followers': '86', 'following': 242,        'img': image_list[1]},
        {'name': 'testname1', 'id': 'testid1', 'avglikesppost': 32, 'postspw': 12,
         'followers': '42345', 'following': 112, 'img': image_list[0]},
        {'name': 'testname2', 'id': 'testid2', 'avglikesppost': 43, 'postspw': 32,
         'followers': '86', 'following': 242,        'img': image_list[1]},
        {'name': 'testname1', 'id': 'testid1', 'avglikesppost': 55, 'postspw': 12,
         'followers': '42345', 'following': 112, 'img': image_list[0]},
        {'name': 'testname2', 'id': 'testid2', 'avglikesppost': 67, 'postspw': 32,
         'followers': '86', 'following': 242,        'img': image_list[1]},
        {'name': 'testname3', 'id': 'testid3', 'avglikesppost': 79, 'postspw': 5,
         'followers': '1593476', 'following': 193,   'img': image_list[2]},
        {'name': 'testname2', 'id': 'testid2', 'avglikesppost': 43, 'postspw': 32,
         'followers': '86', 'following': 242,        'img': image_list[1]},
        {'name': 'testname1', 'id': 'testid1', 'avglikesppost': 55, 'postspw': 12,
         'followers': '42345', 'following': 112, 'img': image_list[0]},
        {'name': 'testname2', 'id': 'testid2', 'avglikesppost': 67, 'postspw': 32,
         'followers': '86', 'following': 242,        'img': image_list[1]},
        {'name': 'testname3', 'id': 'testid3', 'avglikesppost': 79, 'postspw': 5,
         'followers': '1593476', 'following': 193,   'img': image_list[2]},
        {'name': 'testname1', 'id': 'testid1', 'avglikesppost': 32, 'postspw': 12,
         'followers': '42345', 'following': 112, 'img': image_list[0]},
        {'name': 'testname2', 'id': 'testid2', 'avglikesppost': 43, 'postspw': 32,
         'followers': '86', 'following': 242,        'img': image_list[1]},
        {'name': 'testname1', 'id': 'testid1', 'avglikesppost': 55, 'postspw': 12,
         'followers': '42345', 'following': 112, 'img': image_list[0]},
        {'name': 'testname2', 'id': 'testid2', 'avglikesppost': 67, 'postspw': 32,
         'followers': '86', 'following': 242,        'img': image_list[1]},
        {'name': 'testname3', 'id': 'testid3', 'avglikesppost': 79, 'postspw': 5,
         'followers': '1593476', 'following': 193,   'img': image_list[2]},
    ]

    return data
